run:
  timeout: 3m
  skip-files: []
  skip-dirs: []

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    # Deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # Not relevant for this plugin
    - sqlclosecheck
    - rowserrcheck
    - execinquery
    # Duplicates and overly strict rules
    - cyclop
    - bodyclose
    - dupl
    - testpackage
    - tparallel
    - paralleltest
    - nlreturn
    - wsl
    - exhaustive
    - exhaustruct
    - goerr113
    - wrapcheck
    - noctx
    - lll
    - gomnd
    - forbidigo
    - varnamelen

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
